#!/bin/bash

# Autostart System Applications
sxhkd -c ~/.config/berry/sxhkdrc &
feh --bg-scale ~/.config/backgrounds/pine.jpg &
picom --config ~/.config/picom/picom.conf &
bash ~/.config/polybar/launch.sh &
pulseaudio &
dunst &
dunstify -a "Bonsai Linux" "Welcome to a more cultivated Linux experience." &

# Workspaces
berryc name_desktop 0 "  "
berryc name_desktop 1 "  "
berryc name_desktop 2 "  "
berryc name_desktop 3 "  "
berryc name_desktop 4 "  "
berryc name_desktop 5 " 爵 "
berryc name_desktop 6 " ﭮ "
berryc name_desktop 7 "  "
berryc name_desktop 8 "  "
berryc name_desktop 9 "  "

# Set Window Options
berryc border_width       3
berryc inner_border_width 2
berryc title_height       25
berryc top_gap            40
berryc focus_color         3b573d
berryc unfocus_color       74533e
berryc inner_focus_color   3b573d
berryc inner_unfocus_color 74533e
berryc text_focus_color    111111
berryc text_unfocus_color  eeeeee
berryc decorate_new 	"false"
berryc smart_place 		"true"
berryc draw_text   		"true"
berryc edge_lock   		"true"
berryc set_font    		"Hack-11"

###############################
#      Colors Reference       #
###############################
#Color:    #Normal // #Bright #
###############################
#BG/FG:    #101010 // #72A776 # 
#Black:    #101010 // #242424 # 0/08
#Red:      #851E2C // #BD5967 # 1/09
#Green:    #3B573D // #618E64 # 2/10
#Yellow:   #74533E // #C88356 # 3/11
#Blue:     #005F87 // #7A9EC2 # 4/12
#Purple:   #624C8F // #B994E9 # 5/13
#Cyan:     #005f5f // #6DAFB0 # 6/14
#White:    #777777 // #CCCCCC # 7/15
###############################
